site_name: NKU 640
nav:
  - Home: index.md
  - TODO-API:
      - Overview: homework4/README.md
      - Plan: homework4/HW4_plan_stage1.md
      - PHP Implementation:
          - README: homework4/php-version/README.md
          - API Reference: homework4/php-version/API.md
          - Tutorial Slides: homework4/php-version/tutorial.md
          # - Implementation Summary: homework4/php-version/IMPLEMENTATION_SUMMARY.md
  - Quality Software:
      - Overview: homework5/README.md
      - Marp Example: homework5/example-marp.md
theme:
  name: material
extra_css:
  - style.css
extra:
  favicon: favicon.svg
